//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportationAkademiPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAdmin
    {
        public int AdminID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Adminrole { get; set; }
        public Nullable<int> Employee { get; set; }
    
        public virtual TblEmployee TblEmployee { get; set; }
    }
}
